{% set name = 'glacier_lengths' %}
{% set version = '0.1.2' %}

package:
  name: '{{ name | lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/erikmannerfelt/glacier_lengths/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5116efbaeef873cd56db32bd7ad7188bafa7a98336a6471b0169bcd5d2aa3e11

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv'

requirements:
  host:
  - python >=3.7
  - pip
  - shapely
  - numpy
  run:
  - python >=3.7
  - shapely
  - numpy

test:
  imports:
  - glacier_lengths

about:
  home: https://github.com/erikmannerfelt/glacier_lengths
  license: Apache-2.0
  license_file: LICENSE
  summary: Tools to measure glacier lengths statistically
  doc_url: https://glacier-lengths.readthedocs.io
  dev_url: https://github.com/erikmannerfelt/glacier_lengths

extra:
  recipe-maintainers:
  - erikmannerfelt
